package org.example;// Generated by Selenium IDE
import org.junit.Test;

public class CreateGroupTest extends TestBase{

  @Test
  public void testGroupCreation() {
    goToGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("group3", "g", "gr"));
    submitGroupCreation();
    returnToGroupPage();
  }

}
