package org.example;// Generated by Selenium IDE
import org.junit.Test;

public class DeleteGroupTest extends TestBase{

  @Test
  public void testDeleteGroup() {
    goToGroupPage();
    selectGroup();
    deleteSelectedGroups();
    returnToGroupPage();
  }

}
