package org.example.tests;// Generated by Selenium IDE
import org.example.model.GroupData;
import org.example.model.Groups;
import org.junit.Before;
import org.junit.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.equalTo;

public class DeleteGroupTest extends TestBase {

  @Before
  public void ensurePreconditions(){
    app.getNavigationHelper().goToGroupPage();
    if (!app.getGroupHelper().isWhereAGroup()){
      app.getGroupHelper().createGroup(new GroupData().withGroupName("test1"));
    }
  }

  @Test
  public void testDeleteGroup() {
    Groups before = app.getGroupHelper().getAllGroups();

    GroupData deletedGroup = before.iterator().next();
    app.getGroupHelper().deleteGroup(deletedGroup);
    assertThat(app.getGroupHelper().getGroupCount(), equalTo(before.size() - 1));

    Groups after = app.getGroupHelper().getAllGroups();
    assertThat(after, equalTo(before.without(deletedGroup)));
  }

}